spring:

  datasource:
    url: jdbc:mysql://localhost:3306/onlineexam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '0213'
    driver-class-name: com.mysql.cj.jdbc.Driver
  freemarker:
    template-loader-path: classpath:/templates
    #spring.freemarker.template-loader-path=classpath:/templates/
    charset: utf-8
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
server:
  port: 8088

#≈‰÷√mybatis-plus
mybatis-plus:
#≈‰÷√…®√Ëxml
  mapper-locations: classpath:/mapper/*.xml
# µÃÂ…®√Ë£¨∂‡∏ˆpackage”√∂∫∫≈ªÚ’ﬂ∑÷∫≈∑÷∏Ù
  type-aliases-package: com.you.entity
  global-config:
    #¬ﬂº≠…æ≥˝≈‰÷√
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector




