spring:
  thymeleaf:
        enabled: false
        cache: false
        encoding: utf-8
        suffix: .html
        mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/onlineexam?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '0213'
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    enabled: true
    suffix: .ftl
    charset: UTF-8
    template-loader-path: classpath:/templates/
    check-template-location: true
    content-type: text/html
    .expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
server:
  port: 8088


mybatis-plus:
  config:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.you.online_exam.entity
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector





