spring:
  datasource:
    url: jdbc:mysql://localhost:3306/onlineexam?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '0213'
    driver-class-name: com.mysql.jdbc.Driver
